#!/usr/bin/env bash
# Deploy a project with no CI and no registry in the loop: the image is built on
# the production host itself and deployed from local podman storage.
#
# Run it through `wt deploy <project> [target]`, which adds the cross-session
# lock and reports which sibling sessions' work is NOT in the deploy. Directly:
#
#   cd <repo> && bash ~/www/keel-base/tools/deploy/ship.sh [target]
#   SHIP_REF=<sha> SHIP_FORCE=1 bash ~/www/keel-base/tools/deploy/ship.sh   # rollback
#
# The project declares its host and targets in <repo>/deploy/ship.conf:
#
#   PROJECT="signalbots"
#   PROD_HOST="milad@169.58.161.255"
#   PROD_KEY="$HOME/.ssh/signalbots_deploy_key"   # optional
#   PROD_REPO="www/signalbots"                    # path on the host, from $HOME
#   TARGETS="web ingest"                          # first one is the default
#   TARGET_web_IMAGE="localhost/signalbots-web"
#   TARGET_web_CONTEXT="."
#   TARGET_web_FILE="Dockerfile"
#   TARGET_web_DEPLOY="deploy/prod-deploy.sh"
#
# What happens:
#   1. The commit is pushed over SSH straight into the prod checkout, as the ref
#      refs/deploy/main. The host never fetches from GitHub.
#   2. tools/deploy/server-ship.sh is copied to the host and started there in a
#      transient systemd --user unit, which takes the per-project host lock,
#      resets the checkout to the commit, builds the image with podman at the
#      lowest CPU/IO priority and runs the project's own deploy script.
#   3. This script follows the unit's log and exits with its status. The deploy
#      runs on the host, not in this SSH session: if the connection drops it
#      carries on, and the re-attach command is printed at the start.

set -euo pipefail

repo="${KEEL_SHIP_REPO:-$(git rev-parse --show-toplevel)}"
conf="$repo/deploy/ship.conf"
[ -f "$conf" ] || { echo "ship: no $conf — this project is not on the host-build deploy." >&2; exit 2; }

PROJECT=""; PROD_HOST=""; PROD_KEY=""; PROD_REPO=""; TARGETS=""
# shellcheck disable=SC1090
. "$conf"
: "${PROJECT:?ship.conf must set PROJECT}"
: "${PROD_HOST:?ship.conf must set PROD_HOST}"
: "${PROD_REPO:?ship.conf must set PROD_REPO}"
: "${TARGETS:?ship.conf must set TARGETS}"

target="${1:-${TARGETS%% *}}"
case " $TARGETS " in *" $target "*) ;; *) echo "ship: unknown target '$target' (have: $TARGETS)" >&2; exit 2 ;; esac

ssh_opts=(-o ServerAliveInterval=30 -o ServerAliveCountMax=6)
[ -n "$PROD_KEY" ] && ssh_opts+=(-i "$PROD_KEY" -o IdentitiesOnly=yes)

cd "$repo"
ref="${SHIP_REF:-origin/main}"
case "$ref" in
    # Fail loudly rather than ship a stale cached remote branch.
    origin/*) git fetch -q origin "${ref#origin/}" ;;
esac
sha="$(git rev-parse --verify "${ref}^{commit}")"

echo "[ship] $PROJECT/$target at ${sha:0:8} ($(git log -1 --format=%s "$sha"))"
echo "[ship] pushing the commit to $PROD_HOST..."
GIT_SSH_COMMAND="ssh ${ssh_opts[*]}" \
    git push -q --force "$PROD_HOST:$PROD_REPO" "$sha:refs/deploy/main"

state_dir=".cache/$PROJECT-ship"
ssh "${ssh_opts[@]}" "$PROD_HOST" "mkdir -p ~/$state_dir"
scp "${ssh_opts[@]}" -q "$(dirname "$0")/server-ship.sh" "$PROD_HOST:$state_dir/server-ship.sh"

unit="$PROJECT-ship-$target-$(date +%Y%m%d-%H%M%S)"

ssh "${ssh_opts[@]}" "$PROD_HOST" bash -s -- \
    "$unit" "$PROJECT" "$target" "$sha" "$PROD_REPO" "${SHIP_FORCE:-}" <<'REMOTE'
set -euo pipefail
unit="$1"; project="$2"; target="$3"; sha="$4"; prod_repo="$5"; force="${6:-}"
state="$HOME/.cache/$project-ship"
mkdir -p "$state"
log="$state/$unit.log"
rc_file="$state/$unit.rc"
wrapper="$state/$unit.sh"

# The wrapper is written here rather than kept in the repo: it must survive the
# `git reset --hard` it performs, and it must exist before the repo carries it.
cat > "$wrapper" <<EOF
#!/bin/bash
# Generated by keel-base tools/deploy/ship.sh for $unit.
unset INVOCATION_ID
exec >>"$log" 2>&1
if [ "\${SHIP_LOCKED:-}" != 1 ]; then
    echo "[ship] waiting for the $project host deploy lock..."
    # -o: the lock fd is not inherited by anything podman starts, or conmon
    # would hold the lock for the container's whole lifetime.
    SHIP_LOCKED=1 exec flock -o -w 3600 /tmp/$project-ship.lock bash "\$0"
fi
cd "\$HOME/$prod_repo"
last="$state/deployed-$target.sha"
if [ -s "\$last" ] && [ "\$(cat "\$last")" != "$sha" ] \\
   && git merge-base --is-ancestor "$sha" "\$(cat "\$last")" 2>/dev/null \\
   && [ -z "$force" ]; then
    echo "[ship] $sha is older than the deployed \$(cat "\$last"); superseded, nothing to do."
    echo 0 > "$rc_file"; exit 0
fi
git reset --hard -q "$sha" && bash "$state/server-ship.sh" "$target"
rc=\$?
[ \$rc -eq 0 ] && echo "$sha" > "\$last"
echo \$rc > "$rc_file"
exit \$rc
EOF

: > "$log"
# KillMode=process is load-bearing: at the end of the unit systemd would
# otherwise take conmon and rootlessport of the containers the deploy just
# started. RuntimeMaxSec is the backstop for a wedged deploy.
systemd-run --user --quiet --collect --unit="$unit" \
    --property=KillMode=process \
    --property=RuntimeMaxSec=7200 \
    /bin/bash "$wrapper"

echo "[ship] running on $(hostname -s) as unit $unit"
echo "[ship] re-attach if this connection drops: ssh $(whoami)@$(hostname -I | awk '{print $1}') tail -F $log"

tail -n +1 -F "$log" 2>/dev/null &
tailer=$!
while [ "$(systemctl --user show -p ActiveState --value "$unit" 2>/dev/null)" = "active" ]; do
    sleep 5
done
sleep 1
kill "$tailer" 2>/dev/null || true

# Keep the last 30 runs (log + rc + wrapper each).
ls -1t "$state"/"$project"-ship-* 2>/dev/null | tail -n +91 | xargs -r rm -f

rc="$(cat "$rc_file" 2>/dev/null || echo 1)"
if [ "$rc" = "0" ]; then
    echo "[ship] GREEN: $project/$target deployed at ${sha:0:8}"
else
    echo "[ship] FAILED (exit $rc). Full log: $log"
fi
exit "$rc"
REMOTE
